# Generated by Django 5.2.16 on 2026-07-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_alter_releaseorder_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseorder',
            name='status',
            field=models.CharField(choices=[('CREATED', '待触发'), ('TRIGGERING', '触发中'), ('RUNNING', '运行中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='CREATED', max_length=64, verbose_name='发布状态'),
        ),
    ]
